name: Context testing
on: [push,workflow_dispatch]

env:
  token: ${{ secrets.GITHUB_TOKEN }}
  repo: ${{ github.repository }}
  
jobs:
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: installing python Github API
        run: pip install PyGithub
      - name: running script 
        run: |
          ls -la
          echo $pwd
          python test.py 


