name: Context testing
on: workflow_dispatch


jobs:
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: python verson
        run: python --version
