name: Context testing
on: [push,workflow_dispatch]

env:
  token: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: check1
        run: echo $ {{ env.token }}
      - name: checkout
        uses: actions/checkout@v3
      - name: check2
        run: echo ${{ env.token }}
      - name: installing python Github API
        run: pip install PyGithub
      - name: running script 
        run: python test.py  


