name: Context testing
on: workflow_dispatch


jobs:
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: test
        run: echo ${{secrets.GITHUB_TOKEN}}

