name: Context testing
on: workflow_dispatch


jobs:
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: pip list before
        run: pip list
      - name: pip install 
        run: pip install PyGithub
      - name: pip list after 
        run: pip list
